export enum HttpStatusCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  FORBIDDEN_ERROR = 'FORBIDDEN_ERROR',
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR',
  BAD_REQUEST_ERROR = 'BAD_REQUEST_ERROR',
  NOT_FOUND_ERROR = 'NOT_FOUND_ERROR',
  USER_EXISTED = 'USER_EXISTED'
}